# Use postgres/example user/password credentials
version: '3.1'

services:

  mine-sweeper-db:
    image: postgres
    container_name: mine-sweeper-db
    restart: always
    environment:
      POSTGRES_USER: adminsweeper
      POSTGRES_PASSWORD: adminSweeper@05052021
      POSTGRES_DB: minesweeperdb
    ports:
      - 5432:5432

  mine-sweeper-adminer:
    container_name: mine-sweeper-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  mine-sweeper-authentication-api:
    container_name: mine-sweeper-authentication-api
    image: mine-sweeper-authentication-api  
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}    
    build:
      context: .
      dockerfile: MineSweeper.Authentication.Api/Dockerfile
    ports:
      - 8081:8081
    env_file: .env
    depends_on:
      - mine-sweeper-db
    
  mine-sweeper-game-api:
    container_name: mine-sweeper-game-api
    image: minesweeper-game-api  
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}        
    build:
      context: .
      dockerfile: MineSweeper.Game.Api/Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - mine-sweeper-db
      - mine-sweeper-authentication-api
      
  mine-sweeper-monitoring:
    container_name: mine-sweeper-monitoring
    image: minesweeper-monitoring 
    build:
      context: .
      dockerfile: MineSweeper.Monitoring/Dockerfile
    ports:
      - 8083:8083
    depends_on:
      - mine-sweeper-game-api
      - mine-sweeper-authentication-api
      
      
      
   