version: '2'

services:

  mine-sweeper-db:
    image: postgres
    container_name: mine-sweeper-db
    restart: always
    environment:
      POSTGRES_USER: adminsweeper
      POSTGRES_PASSWORD: adminSweeper@05052021
      POSTGRES_DB: minesweeperdb
    ports:
      - 5432:5432

  mine-sweeper-adminer:
    container_name: mine-sweeper-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  mine-sweeper-authentication-api:
    container_name: mine-sweeper-authentication-api
    image: mine-sweeper-authentication-api 
    env_file: .env 
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}    
    build:
      context: .
      dockerfile: MineSweeper.Authentication.Api/Dockerfile
    ports:
      - 8081:8081
    
    depends_on:
      - mine-sweeper-db
    
  mine-sweeper-game-api:
    container_name: mine-sweeper-game-api
    image: mine-sweeper-game-api
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}        
    build:
      context: .
      dockerfile: MineSweeper.Game.Api/Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - mine-sweeper-db
      - mine-sweeper-authentication-api
      
  mine-sweeper-monitoring:
    container_name: mine-sweeper-monitoring
    image: mine-sweeper-monitoring
    build:
      context: .
      dockerfile: MineSweeper.Monitoring/Dockerfile
    ports:
      - 8083:8083
    depends_on:
      - mine-sweeper-game-api
      - mine-sweeper-authentication-api
      
  mine-sweeper-web:
    container_name: mine-sweeper-web
    image: mine-sweeper-web
    env_file: .env
    environment:
      MINESWEEPER_AUTHENTICATION_URL: ${MINESWEEPER_AUTHENTICATION_URL}      
      MINESWEEPER_GAME_URL: ${MINESWEEPER_GAME_URL}
    build:
      context: .
      dockerfile: MineSweeper.Web.React/Dockerfile
    ports:
      - 3000:3000
    volumes:
      # - './Build/MineSweeper.Web.React/:/app'
      - '.:/app'
      - '/app/node_modules'        
    depends_on: 
      - mine-sweeper-authentication-api
      - mine-sweeper-game-api  
      - mine-sweeper-monitoring      
      
   